[tool.poetry]
name = "jieba_pyfast"
version = "1.4.0"
description = "Tokenize Chinese characters"
license = "MIT"
authors = ["snapADDY GmbH <info@snapaddy.com>"]
readme = "README.md"
build = "build.py"

[tool.poetry.dependencies]
python = "3.11.*"

[tool.poetry.dev-dependencies]
isort = "^5.9.2"
black = "^22.6.0"
auditwheel = "^5.1.2"
pycln = "^2.1.1"
pytest = "^7.1.2"
cibuildwheel = "^2.9.0"

[tool.isort]
line_length = 88
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3

[tool.pycln]
all = true
exclude = "__init__.py"

[tool.cibuildwheel]
build = "cp311-*"
test-requires = "pytest"
test-command = "pytest {project}/tests"

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"
