name: CI & CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: pip install cibuildwheel<=3 poetry

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      - name: Deploy wheels
        run: poetry config pypi-token.pypi ${{ secrets.POETRY_PYPI_TOKEN_PYPI }} && poetry publish 
